[build]
  publish = "public"  # El directorio a publicar, típicamente "public" para Laravel
  command = "npm install && npm run prod && composer install && php artisan key:generate && php artisan migrate --force"

[build.environment]
  PHP_VERSION = "8.2"

[context.production.environment]
  PHP_VERSION = "8.2"

[context.deploy-preview.environment]
  PHP_VERSION = "8.2"

[context.branch-deploy.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200