[build]
  publish = "public" 
  command = "composer install && npm install && npm run build"

[build.environment]
  PHP_VERSION = "8.2"

[context.production.environment]
  PHP_VERSION = "8.2"

[context.deploy-preview.environment]
  PHP_VERSION = "8.2"

[context.branch-deploy.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200